world:
- type: robolab
  id: _robolab # Use an underscore in the id to NOT namespace all child entities
  pose: { x: 0, y: 0, z: 0 }

plugins:
  - name: gui_server
    lib: libed_gui_server_plugin.so
    
  - name: tf_publisher
    lib: libed_tf_publisher_plugin.so
    parameters:
      root_frame_id: /marker
      
  - name: rgbd_integration_table
    lib: libed_kinect_plugin.so
    enabled: 1
    parameters:
      topic: /kinect2/hd/rgbd
      
  - name: rgbd_integration_robot
    lib: libed_kinect_plugin.so
    enabled: 1
    parameters:
      topic: /kinect_head/rgbd
      
  - name: perception                                                              
    lib: libed_perception_plugin.so  
    
#  - name: robot_plugin
#    lib: libed_robot_plugin.so
#    parameters:
#        robot_name: pr2
#        urdf_rosparam: robot_description
#        joint_topics:
#          - topic: /joint_states

