- id: 'leap_front_left'
  position:
    x: 0
    y: 0
    z: 0
  orientation:
    roll: 0
    pitch: 0
    yaw: 0
  conn: 'ws://localhost:6437/v6.json'
#- id: 'leap_front_right'
#  position:
#    x: 0.5
#    y: 0
#    z: 0
#  orientation:
#    roll: 0
#    pitch: 0
#    yaw: 0
#  conn: 'ws://localhost:9000/v6.json'
