# this should be faster than using point clouds but it requires OpenGL
sensors:
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /kinect_head/depth_registered/image
    queue_size: 1
    near_clipping_plane_distance: 0.5
    far_clipping_plane_distance: 2.5
    shadow_threshold: 0.2
    padding_scale: 3.0
    padding_offset: 0.03
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /art/n1/kinect2/qhd/image_depth_rect
    queue_size: 1
    near_clipping_plane_distance: 0.5
    far_clipping_plane_distance: 2.5
    shadow_threshold: 0.2
    padding_scale: 3.0
    padding_offset: 0.03
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /art/n2/kinect2/qhd/image_depth_rect
    queue_size: 1
    near_clipping_plane_distance: 0.5
    far_clipping_plane_distance: 2.5
    shadow_threshold: 0.2
    padding_scale: 3.0
    padding_offset: 0.03
