pick:
  - PickFromFeeder
  - PickFromPolygon
place:
  - PlaceToGrid
  - PlaceToPose

using_object:
  - PickFromFeeder
  - PickFromPolygon
  - DrillPoints
  - PlaceToGrid
  - PlaceToPose

using_pose:
  - PickFromFeeder
  - PlaceToPose
  - DrillPoints
  - PlaceToGrid
  - VisualInspection

using_polygon:
  - DrillPoints
  - PickFromPolygon
  - PlaceToGrid

ref_to_pick:
  - VisualInspection

instructions:

  DrillPoints:
      gui:
        package: art_instructions.gui
        learn: DrillPointsLearn
        run: DrillPointsRun
      brain:
        package: art_instructions.brain
      localised_name:
        cs_CZ: Aplikuj lepidlo
        en_US: Aplly glue

  GetReady:
      gui:
        package: art_instructions.gui
        learn: GetReadyLearn
        run: GetReadyRun
      brain:
        package: art_instructions.brain
      localised_name:
        cs_CZ: Připravit
        en_US: Get Ready

  PickFromFeeder:
      gui:
        package: art_instructions.gui
        learn: PickFromFeederLearn
        run: PickFromFeederRun
      brain:
        package: art_instructions.brain
      localised_name:
        cs_CZ: Zvedni z podavače
        en_US: Pick from feeder

  PickFromPolygon:
      gui:
        package: art_instructions.gui
        learn: PickFromPolygonLearn
        run: PickFromPolygonRun
      brain:
        package: art_instructions.brain
      localised_name:
        cs_CZ: Zvedni z oblasti
        en_US: Pick from polygon

  PlaceToGrid:
      gui:
        package: art_instructions.gui
        learn: PlaceToGridLearn
        run: PlaceToGridRun
      brain:
        package: art_instructions.brain
      localised_name:
        cs_CZ: Polož do oblasti
        en_US: Place to grid

  PlaceToPose:
      gui:
        package: art_instructions.gui
        learn: PlaceToPoseLearn
        run: PlaceToPoseRun
      brain:
        package: art_instructions.brain
      localised_name:
        cs_CZ: Polož na místo
        en_US: Place to pose

  VisualInspection:
      gui:
        package: art_instructions.gui
        learn: VisualInspectionLearn
        run: VisualInspectionRun
      brain:
        package: art_instructions.brain
      localised_name:
        cs_CZ: Vizuální kontrola
        en_US: Visual inspection

  WaitForUser:
      gui:
        package: art_instructions.gui
        learn: WaitForUserLearn
        run: WaitForUserRun
      brain:
        package: art_instructions.brain
      localised_name:
        cs_CZ: Počkej na uživatele
        en_US: Wait for user

  WaitUntilUserFinishes:
      gui:
        package: art_instructions.gui
        learn: WaitUntilUserFinishesLearn
        run: WaitUntilUserFinishesRun
      brain:
        package: art_instructions.brain
      localised_name:
        cs_CZ: Počkej až uživatel skončí
        en_US: Wait until user finishes