pick:
  - PickFromFeeder
  - PickFromPolygon
place:
  - PlaceToGrid
  - PlaceToPose
  - PlaceToContainer

using_object:
  - PickFromFeeder
  - PickFromPolygon
  - DrillPoints
  - PlaceToGrid
  - PlaceToPose
  - PlaceToContainer

using_pose:
  - PickFromFeeder
  - PlaceToPose
  - DrillPoints
  - PlaceToGrid
  - VisualInspection

using_polygon:
  - DrillPoints
  - PickFromPolygon
  - PlaceToGrid
  - PlaceToContainer

ref_to_pick:
  - VisualInspection

runnable_during_learning:
  - DrillPoints
  - GetReady
  - PickFromFeeder
  - PickFromPolygon
  - PlaceToGrid
  - PlaceToPose
  - VisualInspection
  - PlaceToContainer


# gui classes are expected in package.gui module
# brain classes are expected in package.brain module

instructions:

  DrillPoints:
      gui:
        package: art_instructions
        learn: DrillPointsLearn
        run: DrillPointsRun
        vis: DrillPointsVis
      brain:
        package: art_instructions
        fsm: Empty  # placeholder - to be removed

  GetReady:
      gui:
        package: art_instructions
        learn: GetReadyLearn
        run: GetReadyRun
      brain:
        package: art_instructions
        fsm: Empty

  PickFromFeeder:
      gui:
        package: art_instructions
        learn: PickFromFeederLearn
        run: PickFromFeederRun
        vis: PickFromFeederVis
      brain:
        package: art_instructions
        fsm: Empty

  PickFromPolygon:
      gui:
        package: art_instructions
        learn: PickFromPolygonLearn
        run: PickFromPolygonRun
        vis: PickFromPolygonVis
      brain:
        package: art_instructions
        fsm: Empty

  PlaceToGrid:
      gui:
        package: art_instructions
        learn: PlaceToGridLearn
        run: PlaceToGridRun
        vis: PlaceToGridVis
      brain:
        package: art_instructions
        fsm: Empty

  PlaceToPose:
      gui:
        package: art_instructions
        learn: PlaceToPoseLearn
        run: PlaceToPoseRun
        vis: PlaceToPoseVis
      brain:
        package: art_instructions
        fsm: Empty

  VisualInspection:
      gui:
        package: art_instructions
        learn: VisualInspectionLearn
        run: VisualInspectionRun
      brain:
        package: art_instructions
        fsm: Empty

  WaitForUser:
      gui:
        package: art_instructions
        learn: WaitForUserLearn
        run: WaitForUserRun
      brain:
        package: art_instructions
        fsm: Empty

  WaitUntilUserFinishes:
      gui:
        package: art_instructions
        learn: WaitUntilUserFinishesLearn
        run: WaitUntilUserFinishesRun
      brain:
        package: art_instructions
        fsm: Empty

  PlaceToContainer:
      gui:
          package: art_instructions
          learn: PlaceToContainerLearn
          run: PlaceToContainerRun
      brain:
          package: art_instructions
          fsm: Empty